/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { RGB, RGBEvent } from "./utils/interfaces";
export namespace Components {
    interface ColorPicker {
        "label"?: string;
        "uniqueId": string;
        "value": RGB;
    }
    interface ColorSwatch {
        "label"?: string;
        "value": RGB;
    }
    interface HomePage {
    }
    interface TSlider {
        "label"?: string;
        "uniqueId": string;
        "value": string;
    }
}
declare global {
    interface HTMLColorPickerElement extends Components.ColorPicker, HTMLStencilElement {
    }
    var HTMLColorPickerElement: {
        prototype: HTMLColorPickerElement;
        new (): HTMLColorPickerElement;
    };
    interface HTMLColorSwatchElement extends Components.ColorSwatch, HTMLStencilElement {
    }
    var HTMLColorSwatchElement: {
        prototype: HTMLColorSwatchElement;
        new (): HTMLColorSwatchElement;
    };
    interface HTMLHomePageElement extends Components.HomePage, HTMLStencilElement {
    }
    var HTMLHomePageElement: {
        prototype: HTMLHomePageElement;
        new (): HTMLHomePageElement;
    };
    interface HTMLTSliderElement extends Components.TSlider, HTMLStencilElement {
    }
    var HTMLTSliderElement: {
        prototype: HTMLTSliderElement;
        new (): HTMLTSliderElement;
    };
    interface HTMLElementTagNameMap {
        "color-picker": HTMLColorPickerElement;
        "color-swatch": HTMLColorSwatchElement;
        "home-page": HTMLHomePageElement;
        "t-slider": HTMLTSliderElement;
    }
}
declare namespace LocalJSX {
    interface ColorPicker {
        "label"?: string;
        "onColorPickerValueChange"?: (event: CustomEvent<RGBEvent>) => void;
        "uniqueId"?: string;
        "value"?: RGB;
    }
    interface ColorSwatch {
        "label"?: string;
        "value"?: RGB;
    }
    interface HomePage {
    }
    interface TSlider {
        "label"?: string;
        "onSliderValueChange"?: (event: CustomEvent<number>) => void;
        "uniqueId"?: string;
        "value"?: string;
    }
    interface IntrinsicElements {
        "color-picker": ColorPicker;
        "color-swatch": ColorSwatch;
        "home-page": HomePage;
        "t-slider": TSlider;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "color-picker": LocalJSX.ColorPicker & JSXBase.HTMLAttributes<HTMLColorPickerElement>;
            "color-swatch": LocalJSX.ColorSwatch & JSXBase.HTMLAttributes<HTMLColorSwatchElement>;
            "home-page": LocalJSX.HomePage & JSXBase.HTMLAttributes<HTMLHomePageElement>;
            "t-slider": LocalJSX.TSlider & JSXBase.HTMLAttributes<HTMLTSliderElement>;
        }
    }
}
